### ISSUE TITLE
Research Methodology

### ISSUE THREAD

**Issue by jwestw** [james-westwood/SDG_11.2.1#13]
@jwestw  to research the methodology used by other govt. statistical departments for this indicator.

**Comment by jwestw** [comment]
A useful write up of methodology on 11.2.1 here:
[Metadata on SDG Indicator 11.2.1 by United nations human settlements program](https://unhabitat.org/sites/default/files/2020/06/metadata_on_sdg_indicator_11.2.1.pdf)

**Comment by jwestw** [comment]
More note on data collection and methodology here: 

[https://unstats.un.org/sdgs/metadata/files/Metadata-11-02-01.pdf](https://unstats.un.org/sdgs/metadata/files/Metadata-11-02-01.pdf)

**Comment by jwestw** [comment]
A discussion of methodogy for 11.2.1 and a step by step walk-through of steps of achieving an answer: [Update on Progress of Monitoring SDG 11.2.1 “Access to Public Transport”](https://www.unece.org/fileadmin/DAM/trans/doc/2019/wp6/Presentations/UN_HABITATtransport_11.2.1_Monitoring_SDG_UNCE_workshop_V2.pdf)

**Comment by jwestw** [comment]
From page 6 onwards here:
(Swedish example on 11.2.1, Access to public transport by Marie Haldorson)[http://ggim.un.org/meetings/2018-International-Seminar-Kenya/documents/02_5th%20IAEG-SDG_WGGI_Swedish_example_Haldorson.pdf]

**Comment by jwestw** [comment]
This is the Austrian method I was talking about: https://www.efgs.info/11-2-1-austria/

Note the section on "Network distance" that is worth looking at to understand why they didn't use a network approach.

**Comment by jwestw** [comment]
The [Norwary method](https://www.efgs.info/11-2-1-norway-test-page/) is also very useful and interesting.

**Comment by jwestw** [comment]
[Estonia's write up on 11..2.1 ](https://www.efgs.info/11-2-1-estonia/) is great. 

The section on "Results based on national criteria of convenient accessibility" is a really interesting discussion of what makes a public transport system convenient.

**Comment by jwestw** [comment]
Page 38-40 on [this pdf by the Chinese academy ](http://www.xinhuanet.com/english/download/BigEarthDataSupportSDGs.pdf) of sciences is worth a read too.

**Comment by jwestw** [comment]
@jwestw to speak to SDG Data team to find out which methodology is required and they have identified a topic expert.

**Comment by james-westwood** [comment]
As long as we are using what is published on EFGS and publish our own steps of the calculation followed, that should be acceptable. Quality and methodology document to be produced at the end of process.

**Comment by jwestw** [comment]
Closing because research is completed.
