### ISSUE TITLE
Change coordinate reference system for projections

### ISSUE THREAD

**Issue by jwestw** [james-westwood/SDG_11.2.1#14]
@jwestw to change crs of projections to 27700

**Comment by jwestw** [comment]
Advice from Musa:
- Since the objective is to run a buffer based on distance, it would be best to use the British National Grid reference system (OSGB36 datum) (27700).
- WGS84 is based on degrees and minutes and generally not as good for distance based analysis.
- Switch from WGS84 (4326) to the British National Grid  system for the analysis from this point going forward.
- Using the British National Grid (based on meters) buffering will be a simple task. Only need to pass 500 onto your script for the 500m buffer.

Based on coversations this should be something like:
`gdf.geometry.buffer(500)`

- On the stops, pass the Eastings and Northings as the X and Y variables respectively, replacing the Latitude and Longitude used before.
- Check that this is projected correctly by running `Stops.crs` for example 
- Make sure that the OA centroids also have a matching projection.

**Comment by james-westwood** [comment]
This is done
