### ISSUE TITLE
Get population data for Birmingham

### ISSUE THREAD

**Issue by jwestw** [james-westwood/SDG_11.2.1#3]
- Take the population estimates for the west mids and create new csv sheet of pure data
- import all of WMs data into pandas

**Comment by jwestw** [comment]
[Link to population estimates](https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates/datalist?:uri=peoplepopulationandcommunity/populationandmigration/populationestimates/datalist&:uri=peoplepopulationandcommunity/populationandmigration/populationestimates/datalist&fromDateDay=&fromDateMonth=&fromDateYear=&query=output%20areas&size=10&sortBy=release_date&toDateDay=&toDateMonth=&toDateYear=&page=1)

**Comment by jwestw** [comment]
1) Using the output area csv, join to population estimates data on output area `OA11CD` 
2) code would be something like `df.LAD11NM.str.contains("Birmingham")` which should give me just Birmingham. 
3) same process for output area centroid. Join it with the output area csv. 
4) join Birmingham centroids to Birmingham population (output from the 2nd step).

**Comment by jimzz9** [comment]
[Source of the West mids data](https://www.ons.gov.uk/file?uri=%2fpeoplepopulationandcommunity%2fpopulationandmigration%2fpopulationestimates%2fdatasets%2fcensusoutputareaestimatesinthewestmidlandsregionofengland%2fmid2019sape22dt10e/sape22dt10emid2019westmidlands.zip)

**Comment by jimzz9** [comment]
I believe this is all done now too.
