### ISSUE TITLE
Create function for urban clustering

### ISSUE THREAD

**Issue by james-westwood** [james-westwood/SDG_11.2.1#38]
- Need help from Geospatial on this. 
- Do functions for this already exist?
- What is supplied, what is returned?

**Comment by james-westwood** [comment]
Interesting articles related to the development of this:
- https://lixun910.github.io/pygeoda/spatial_clustering.html
- https://nbviewer.jupyter.org/github/pysal/esda/blob/master/notebooks/Spatial%20Autocorrelation%20for%20Areal%20Unit%20Data.ipynb
- https://darribas.org/gds_scipy16/ipynb_md/07_spatial_clustering.html

**Comment by jwestw** [comment]
data for urban/rural: https://geoportal.statistics.gov.uk/search?collection=Dataset&sort=name&tags=all(PRD_RUC_OA)

pick 2011 data

**Comment by jwestw** [comment]
OA urban rural classification: geoportal.statistics.gov.uk/datasets/rural-urban-classification-2011-of-output-areas-in-england-and-wales

**Comment by jwestw** [comment]
Finished with 
Merge pull request #68 from james-westwood/urban_cluster_#38
