### ISSUE TITLE
Put ages into buckets

### ISSUE THREAD

**Issue by james-westwood** [james-westwood/SDG_11.2.1#7]
Check if functions exist to bucket-ize values
If no function exists, write a function to bucketize the age values. 
Looking at other SDG indicators, buckets should be:

From [Indicator 3.6.1 ](https://sdgdata.gov.uk/3-6-1/)

- 4 and under
- 5 to 7
- 8 to 11
- 12 to 15
- 16 to 19
- 20 to 29
- 30 to 39
- 40 to 49
- 50 to 59
- 60 to 69
- 70 to 79
- 80 and over

And from [Indicator 3.4.2](https://sdgdata.gov.uk/3-4-2/)

- 10 to 14
- 15 to 19
- 20 to 24
- 25 to 29
- 30 to 34
- 35 to 39
- 40 to 44
- 45 to 49
- 50 to 54
- 55 to 59
- 60 to 64
- 65 to 69
- 70 to 74
- 75 to 79
- 80 to 84
- 85 to 89
- 90 and over

These do not agree with each other. Need to ask.

**Comment by jwestw** [comment]
@jwestw to speak to SDG data team about which age brackets to use.

**Comment by james-westwood** [comment]
Decided to use 5 year age groups. 

Explore other groupings to see if anything stands out as interesting.

**Comment by james-westwood** [comment]
I found some strange data after isolating the the counts of people (from census data) by age.It appeared because out of many thousands of values it is the only one with a comma in it and wouldn't convert to an integer. 

The problem is in column 19 (for 19 years old)

![image](https://user-images.githubusercontent.com/49570694/104775926-17f84680-5771-11eb-80cb-ba0077724d25.png)

The value is much higher than those around it and other typical values I've seen. 

So I have forced it to convert, and have plotted the counts of the integer values. 

![image](https://user-images.githubusercontent.com/49570694/104776094-6a396780-5771-11eb-9b18-759adce295f3.png)

And this is the plot, hovering over the problem value: 

![image](https://user-images.githubusercontent.com/49570694/104776409-f2b80800-5771-11eb-9279-7263d57d3501.png)

This outlier looks like it might be erroneous.

**Comment by james-westwood** [comment]
I tested the method that I created and am quite happy with it efficiency. 

![image](https://user-images.githubusercontent.com/49570694/105519749-b59fc880-5cd1-11eb-9c94-f2698c603103.png)

And dropping the original columns gets the dataframe I want. 

![image](https://user-images.githubusercontent.com/49570694/105520075-1deeaa00-5cd2-11eb-9bf7-43b602be25be.png)
